hf-token: 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

datasets:
  - path: ahsanirfan961/title-content-dataset
    type: input

  - path: ahsanirfan961/sentence-similarity-output
    type: output

models:
  - path: microsoft/Phi-3.5-mini-instruct
    type: description


input-batch-size: 1
max-tokens: 512
temperature: 0.7

