gpt4-key: "sk-None-ODWdiqGBT8hipSb13ynBT3BlbkFJgiasGXdbhT3h4hCT4EpO"

input-batch-size: 1
max-tokens: 1024
temperature: 0.7

models:
  arena-learning:
    answer-gen:
      - "microsoft/Phi-3-mini-4k-instruct"
      - "Doctor-Shotgun/TinyLlama-1.1B-32k-Instruct"
      - "Qwen/Qwen2-7B-Instruct"
    ranking: "gpt-4o-mini"
      