
datasets:


models:
  - path: microsoft/Phi-3-mini-4k-instruct
    type: response

  - path: Doctor-Shotgun/TinyLlama-1.1B-32k-Instruct
    type: response
  - path: Qwen/Qwen2-7B-Instruct
    type: response

  - path: gpt-4o-mini
    type: rank
       
gpt4-key: sk-None-ODWdiqGBT8hipSb13ynBT3BlbkFJgiasGXdbhT3h4hCT4EpO

input-batch-size: 1
max-tokens: 1024
temperature: 0.7